### ISSUE TITLE
security breach

### ISSUE THREAD

**Issue by ChafikHadjAbdouRazack** [hellomasonite/masonite-forum#5]
Hi. Nice job for the forum. I did little manipulation and I realized that it is possible to switch accounts just by changing the user's id in the url. And also for an id that does not exist we get an error page.

**Comment by nioperas06** [comment]
Hi! Can you share more details about when you're changing user's `id`? And we should throw and `404` exception when id that does not exist 👍

**Comment by ChafikHadjAbdouRazack** [comment]
@nioperas06 When I am logged into my account and I consult my profile I can switch between profiles by changing the id in the URL. Also if the user does not exist we have an error page.

**Comment by ChafikHadjAbdouRazack** [comment]
![Capture d’écran 2019-05-28 à 21 56 21](https://user-images.githubusercontent.com/24951221/58515460-6f106880-8194-11e9-8dc1-9ef3f8b5cee2.png)
![Capture d’écran 2019-05-28 à 21 56 05](https://user-images.githubusercontent.com/24951221/58515465-72a3ef80-8194-11e9-8376-4b4159be5cb7.png)

**Comment by ChafikHadjAbdouRazack** [comment]
Is it not possible to use request.user () instead to get the information of the current user instead of using id?

**Comment by nioperas06** [comment]
I'll just throw a 404 exception.

**Comment by ChafikHadjAbdouRazack** [comment]
@nioperas06 OK
